Avoid Error data/isins_missing ... does not exist (#11)
> Error: 'data/isins_missing_bbg_data.csv' does not exist in current working directory ('/bound').

@jdhoffa mentioned this file is missplaced but we didn't discuss how to
handle it. It seems to be required so I add it.